# Inspect Agent Data

Quick visual sanity check of every CSV under `data/agent_data/` — one cell
per file, each showing `.head()`. Re-run `python fleet_agent/preprocessing.py`
first if you don't see this, or if the file list below is stale (this
notebook lists whatever `agent_data/` contains at the time it was built —
add/remove cells if the set of months changes).

In [1]:
import sys
sys.path.append("..")

import pandas as pd
from pathlib import Path
from gps_lib import config

AGENT_DATA_DIR = Path(config.DATA_DIR) / "agent_data"
pd.set_option("display.max_columns", 25)


def head(filename: str, n: int = 5):
    path = AGENT_DATA_DIR / filename
    if not path.exists():
        print(f"{filename} not found under {AGENT_DATA_DIR} — run `python fleet_agent/preprocessing.py` first.")
        return None
    df = pd.read_csv(path, dtype={"tracker_id": str})
    print(f"{filename} — {df.shape[0]} rows x {df.shape[1]} cols")
    return df.head(n)


print("Files currently in data/agent_data/:")
for p in sorted(AGENT_DATA_DIR.glob("*.csv")):
    print(" ", p.name)

Files currently in data/agent_data/:
  daily_2025-07.csv
  daily_2025-08.csv
  daily_2025-09.csv
  daily_2025-10.csv
  daily_2025-11.csv
  monthly_2025.csv
  routes_2025-07.csv
  routes_2025-08.csv
  routes_2025-09.csv
  routes_2025-10.csv
  routes_2025-11.csv
  tracker_list_bn.csv
  zone_diameter_bn.csv
  zone_qa_2025-07.csv
  zone_qa_2025-08.csv
  zone_qa_2025-09.csv
  zone_qa_2025-10.csv
  zone_qa_2025-11.csv

## Reference data (BN sub-fleet / zones)

In [2]:
head("tracker_list_bn.csv")

tracker_list_bn.csv — 48 rows x 16 cols

,id,label,group_id,tag_bindings,clone,source_id,source_device_id,source_model,source_blocked,source_tariff_id,source_phone,source_status_listing_id,source_creation_date,source_tariff_end_date,technic_type,technic_m_type
0,20505,BN70 Howo-430,2571,[],False,9897,359633107780244,telfmb125,False,1,97689723630,NaN,2021-01-29,2025-11-06,dump,bn
1,20506,BN72 Howo-430,2571,[],False,9901,354017111774507,telfmb125,True,6,97689727674,NaN,2021-01-29,2025-07-19,dump,bn
2,20507,BN71 Howo-430,2571,[],False,9902,352016706144755,telfmb125,False,1,97689705801,NaN,2021-01-29,2025-11-06,dump,bn
3,20800,BN69 Howo-430,2571,[],False,10043,354017111716649,telfmb125,False,1,97689728264,NaN,2021-02-24,2025-11-06,dump,bn
4,34065,BN97 /67-87УЕК/,2571,[],False,15088,357544375140817,telfmb125,False,1,97686704839,NaN,2022-10-21,2025-11-06,dump,bn

In [3]:
head("zone_diameter_bn.csv")

zone_diameter_bn.csv — 3 rows x 4 cols

   zone_id                              label zone_material_type   diameter_m
0    25685              Баруун наран овоолго                  bn   428.876963
1    25559   Баруун наран ачилтын бүс  /Зүүн/                 bn  1051.438131
2    27838  Баруун наран ачилтын бүс /Баруун/                 bn  1455.745051

## Daily (one row per date, tracker_id)

In [4]:
head("daily_2025-07.csv")

daily_2025-07.csv — 441 rows x 19 cols

,date,tracker_id,truck,total_dt_hr,pct_transit,pct_operating,pct_queuing,pct_unplanned_idle,dbscan_unplanned_idle_share,n_cycles,cycle_mean_min,cycle_median_min,cycle_p90_min,cycle_total_h,haul_mean_min,dump_mean_min,return_mean_min,cycle_km_mean,total_km
0,2025-07-01,ALL,ALL,284.68,33.9,6.9,0.0,59.2,0.802,42,169.2,152.0,289.1,118.5,73.5,8.6,87.1,70.72,2970.0
1,2025-07-01,20505,BN70 Howo-430,24.00,54.2,10.0,0.1,35.6,0.743,7,167.4,125.0,285.6,19.5,76.0,8.2,83.2,69.38,486.0
2,2025-07-01,20507,BN71 Howo-430,23.38,16.7,4.2,0.0,79.1,0.853,1,134.4,134.4,134.4,2.2,71.6,0.0,62.8,70.04,70.0
3,2025-07-01,20800,BN69 Howo-430,24.00,30.2,5.6,0.0,64.2,0.852,2,171.0,171.0,217.2,5.7,68.0,5.7,97.4,73.85,148.0
4,2025-07-01,34065,BN97 /67-87УЕК/,23.99,24.6,9.1,0.0,66.3,0.772,2,163.5,163.5,166.5,5.5,81.5,19.8,62.2,70.51,141.0

In [5]:
head("daily_2025-08.csv")

daily_2025-08.csv — 765 rows x 19 cols

,date,tracker_id,truck,total_dt_hr,pct_transit,pct_operating,pct_queuing,pct_unplanned_idle,dbscan_unplanned_idle_share,n_cycles,cycle_mean_min,cycle_median_min,cycle_p90_min,cycle_total_h,haul_mean_min,dump_mean_min,return_mean_min,cycle_km_mean,total_km
0,2025-08-01,ALL,ALL,527.43,37.9,5.7,0.1,56.4,1.000,79,197.2,184.3,313.4,259.7,83.2,14.8,99.3,70.54,5572.0
1,2025-08-01,20505,BN70 Howo-430,23.72,45.2,8.7,0.0,46.1,0.750,4,187.2,178.0,249.7,12.5,81.7,6.9,98.6,70.28,281.0
2,2025-08-01,20507,BN71 Howo-430,23.98,22.1,2.7,0.0,75.2,0.896,1,120.9,120.9,120.9,2.0,59.1,5.6,56.2,70.63,71.0
3,2025-08-01,20800,BN69 Howo-430,23.91,41.8,4.2,0.2,53.8,1.000,3,182.1,184.7,230.3,9.1,69.7,5.8,106.7,69.62,209.0
4,2025-08-01,34065,BN97 /67-87УЕК/,23.75,50.0,7.4,0.2,42.4,1.000,5,262.5,282.1,334.3,21.9,112.6,48.9,101.1,71.77,359.0

In [6]:
head("daily_2025-09.csv")

daily_2025-09.csv — 830 rows x 19 cols

,date,tracker_id,truck,total_dt_hr,pct_transit,pct_operating,pct_queuing,pct_unplanned_idle,dbscan_unplanned_idle_share,n_cycles,cycle_mean_min,cycle_median_min,cycle_p90_min,cycle_total_h,haul_mean_min,dump_mean_min,return_mean_min,cycle_km_mean,total_km
0,2025-09-01,ALL,ALL,520.19,31.5,5.4,0.1,63.0,0.803,26,176.1,163.5,248.2,76.3,74.3,9.6,92.2,71.37,1856.0
1,2025-09-01,20505,BN70 Howo-430,23.75,55.8,6.8,0.0,37.4,1.000,2,202.9,202.9,225.6,6.8,69.5,7.0,126.4,72.63,145.0
2,2025-09-01,20507,BN71 Howo-430,23.90,34.7,3.2,0.0,62.1,0.854,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-09-01,20800,BN69 Howo-430,23.99,60.1,8.9,0.4,30.6,1.000,3,190.7,180.4,227.5,9.5,76.0,7.6,107.1,70.03,210.0
4,2025-09-01,34065,BN97 /67-87УЕК/,23.75,18.4,1.8,0.0,79.9,0.871,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
head("daily_2025-10.csv")

daily_2025-10.csv — 937 rows x 19 cols

,date,tracker_id,truck,total_dt_hr,pct_transit,pct_operating,pct_queuing,pct_unplanned_idle,dbscan_unplanned_idle_share,n_cycles,cycle_mean_min,cycle_median_min,cycle_p90_min,cycle_total_h,haul_mean_min,dump_mean_min,return_mean_min,cycle_km_mean,total_km
0,2025-10-01,ALL,ALL,623.38,38.1,6.4,3.3,52.2,1.000,109,169.7,153.7,238.5,308.3,75.1,12.3,82.3,70.70,7706.0
1,2025-10-01,20505,BN70 Howo-430,23.91,53.0,3.4,4.7,38.9,0.903,4,156.1,144.2,202.3,10.4,75.6,6.7,73.8,70.09,280.0
2,2025-10-01,20507,BN71 Howo-430,23.20,41.7,4.3,1.0,53.0,1.000,3,178.3,177.4,208.2,8.9,85.5,9.5,83.3,70.05,210.0
3,2025-10-01,34065,BN97 /67-87УЕК/,23.94,50.0,10.4,2.3,37.3,1.000,5,174.2,162.9,216.2,14.5,75.4,25.1,73.7,70.14,351.0
4,2025-10-01,38061,BN117 /71-23 УНТ/,23.95,51.2,7.8,2.7,38.3,1.000,4,175.2,162.2,213.3,11.7,83.8,22.1,69.3,70.98,284.0

In [8]:
head("daily_2025-11.csv")

daily_2025-11.csv — 709 rows x 19 cols

,date,tracker_id,truck,total_dt_hr,pct_transit,pct_operating,pct_queuing,pct_unplanned_idle,dbscan_unplanned_idle_share,n_cycles,cycle_mean_min,cycle_median_min,cycle_p90_min,cycle_total_h,haul_mean_min,dump_mean_min,return_mean_min,cycle_km_mean,total_km
0,2025-11-01,ALL,ALL,500.02,42.0,9.8,0.1,48.1,1.000,96,173.0,153.0,264.0,276.9,72.8,13.5,86.7,70.19,6738.0
1,2025-11-01,20505,BN70 Howo-430,23.62,14.1,0.0,0.0,85.9,1.000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-11-01,20507,BN71 Howo-430,23.89,25.5,0.0,0.0,74.5,1.000,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-11-01,34065,BN97 /67-87УЕК/,23.99,48.9,10.9,0.1,40.1,1.000,6,159.8,151.3,190.7,16.0,70.7,19.0,70.2,70.59,424.0
4,2025-11-01,38061,BN117 /71-23 УНТ/,11.11,53.7,11.7,0.1,34.5,0.642,2,195.3,195.3,200.1,6.5,104.4,16.0,74.9,69.52,139.0

## Routes (load/unload share per month)

In [9]:
head("routes_2025-07.csv")

routes_2025-07.csv — 1 rows x 13 cols

,load_zone,unload_zone,load_mat,unload_mat,cycles,haul_km,cycle_km,haul_min,cycle_min,straight_km,load,unload,share_pct
0,25559,25685,bn,bn,1447,34.5,70.39,73.0,170.8,25.78,Баруун наран ачилтын бүс /Зүүн/,Баруун наран овоолго,100.0

In [10]:
head("routes_2025-08.csv")

routes_2025-08.csv — 1 rows x 13 cols

,load_zone,unload_zone,load_mat,unload_mat,cycles,haul_km,cycle_km,haul_min,cycle_min,straight_km,load,unload,share_pct
0,25559,25685,bn,bn,2335,34.33,70.36,73.4,174.1,25.78,Баруун наран ачилтын бүс /Зүүн/,Баруун наран овоолго,100.0

In [11]:
head("routes_2025-09.csv")

routes_2025-09.csv — 1 rows x 13 cols

,load_zone,unload_zone,load_mat,unload_mat,cycles,haul_km,cycle_km,haul_min,cycle_min,straight_km,load,unload,share_pct
0,25559,25685,bn,bn,2279,34.38,70.54,73.0,169.9,25.78,Баруун наран ачилтын бүс /Зүүн/,Баруун наран овоолго,100.0

In [12]:
head("routes_2025-10.csv")

routes_2025-10.csv — 1 rows x 13 cols

,load_zone,unload_zone,load_mat,unload_mat,cycles,haul_km,cycle_km,haul_min,cycle_min,straight_km,load,unload,share_pct
0,25559,25685,bn,bn,2715,34.36,70.47,72.3,172.0,25.78,Баруун наран ачилтын бүс /Зүүн/,Баруун наран овоолго,100.0

In [13]:
head("routes_2025-11.csv")

routes_2025-11.csv — 1 rows x 13 cols

,load_zone,unload_zone,load_mat,unload_mat,cycles,haul_km,cycle_km,haul_min,cycle_min,straight_km,load,unload,share_pct
0,25559,25685,bn,bn,2389,34.45,70.55,74.9,181.8,25.78,Баруун наран ачилтын бүс /Зүүн/,Баруун наран овоолго,100.0

## Zone QA (stopped-ping count per month)

In [14]:
head("zone_qa_2025-07.csv")

zone_qa_2025-07.csv — 3 rows x 5 cols

,zone_id,label,zone_material_type,zone_load_type,n_stopped_pings
0,27838,Баруун наран ачилтын бүс /Баруун/,bn,load,0
1,25685,Баруун наран овоолго,bn,unload,3986
2,25559,Баруун наран ачилтын бүс /Зүүн/,bn,load,7310

In [15]:
head("zone_qa_2025-08.csv")

zone_qa_2025-08.csv — 3 rows x 5 cols

,zone_id,label,zone_material_type,zone_load_type,n_stopped_pings
0,27838,Баруун наран ачилтын бүс /Баруун/,bn,load,0
1,25685,Баруун наран овоолго,bn,unload,5875
2,25559,Баруун наран ачилтын бүс /Зүүн/,bn,load,11570

In [16]:
head("zone_qa_2025-09.csv")

zone_qa_2025-09.csv — 3 rows x 5 cols

,zone_id,label,zone_material_type,zone_load_type,n_stopped_pings
0,27838,Баруун наран ачилтын бүс /Баруун/,bn,load,0
1,25685,Баруун наран овоолго,bn,unload,5577
2,25559,Баруун наран ачилтын бүс /Зүүн/,bn,load,15516

In [17]:
head("zone_qa_2025-10.csv")

zone_qa_2025-10.csv — 3 rows x 5 cols

,zone_id,label,zone_material_type,zone_load_type,n_stopped_pings
0,27838,Баруун наран ачилтын бүс /Баруун/,bn,load,0
1,25685,Баруун наран овоолго,bn,unload,10051
2,25559,Баруун наран ачилтын бүс /Зүүн/,bn,load,19858

In [18]:
head("zone_qa_2025-11.csv")

zone_qa_2025-11.csv — 3 rows x 5 cols

,zone_id,label,zone_material_type,zone_load_type,n_stopped_pings
0,27838,Баруун наран ачилтын бүс /Баруун/,bn,load,0
1,25685,Баруун наран овоолго,bn,unload,8651
2,25559,Баруун наран ачилтын бүс /Зүүн/,bn,load,19638

## Monthly rollup (one row per month, tracker_id)

In [19]:
head("monthly_2025.csv")

monthly_2025.csv — 149 rows x 16 cols

,month,tracker_id,truck,n_days,total_dt_hr,pct_transit,pct_operating,pct_queuing,pct_unplanned_idle,dbscan_unplanned_idle_share,n_cycles,cycle_mean_min,cycle_median_min,cycle_p90_min,cycle_total_h,total_km
0,2025-07,ALL,ALL,31,10053.5,34.7,5.9,0.2,59.1,0.860,1447,170.8,152.1,267.7,4119.0,101849.0
1,2025-07,20505,BN70 Howo-430,31,743.9,37.4,5.5,0.2,56.9,0.876,130,173.2,149.2,254.7,375.0,9169.0
2,2025-07,20507,BN71 Howo-430,25,744.0,27.5,6.1,0.2,66.1,0.843,81,175.8,163.9,238.3,237.2,5671.0
3,2025-07,20800,BN69 Howo-430,31,743.8,50.3,6.7,0.4,42.6,0.813,166,170.5,157.3,237.1,471.5,11687.0
4,2025-07,34065,BN97 /67-87УЕК/,31,744.0,30.7,5.8,0.3,63.3,0.809,67,197.7,194.2,231.0,220.9,4731.0